c_stdlib_version:    # [unix]
  - '11.0'           # [osx]
  - "2.34"           # [linux]
  - "2.34"           # [linux]
MACOSX_SDK_VERSION:  # [osx]
  - '26.1'           # [osx]

blas_impl:
  - mkl        # [(linux and not aarch64) or win]
  - openblas   # [linux and aarch64]
  - accelerate # [osx]
