c_stdlib_version:    # [osx]
  - '11.0'           # [osx]
MACOSX_SDK_VERSION:  # [osx]
  - '26.1'           # [osx]
c_stdlib_version:  # [linux]
  - "2.34"         # [linux]
  - "2.34"         # [linux]

blas_impl:
  - mkl        # [(linux and not aarch64) or win]
  - openblas   # [linux and aarch64]
  - accelerate # [osx]
